### ISSUE TITLE
Unnecessary cast to int

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/chronologic#15]
# DayToken.sol

https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L411
`contributors[toId].totalTransferredDay = contributors[toId].totalTransferredDay + int(_value);`

`_value` is an uint, it will always be a positive number, there is no reason to cast it to an int

**Comment by matt-lough** [comment]
Also happens here https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L376

**Comment by matt-lough** [comment]
These lines of code should probably be using safe math

**Comment by rohendra** [comment]
rejected: can’t add int and uint, casting needed

**Comment by rstormsf** [comment]
@rohendra it will be rejected because:
https://github.com/BlockchainLabsNZ/chronologic/blob/dev/contracts/DayToken.sol#L41 is also `int`
Any reason you use `int` for `totalTransferredDay` 
you should probably have them both `uint`

**Comment by rohendra** [comment]
@rstormsf totalTransferredDay is used to track net transfer from or to any address. So it can be negative also if tokens transferred from this address is more than tokens transferred to this address.
This is possible because Minting process can increase total balance which can then be transferred to some other addresss. totalTransferredDay variable is used so that we can track total minted coins. This variable has to be int because of above reasons.

**Comment by matt-lough** [comment]
@rohendra That makes sense to me, closing this issue.
